# Données {-}


#### Données du cours{-}

Les liens suivants vous dirigerons directement vers les données utilisées pour chaque module

<br>

* [Module 1](https://github.com/sci1031/sci1031/blob/master/Module1/Module1_donnees.zip)
* [Module 2](https://github.com/sci1031/sci1031/blob/master/Module2/Module2_donnees.zip)
* [Module 3](https://github.com/sci1031/sci1031/blob/master/Module3/Module3_donnees.zip)
* [Module 4](https://github.com/sci1031/sci1031/blob/master/Module4/Module4_donnees.zip)
* [Module 5](https://github.com/sci1031/sci1031/blob/master/Module5/Module5_donnees.zip)
* [Module 6](https://github.com/sci1031/sci1031/blob/master/Module6/Module6_donnees.zip)
* [Module 7](https://github.com/sci1031/sci1031/blob/master/Module7/Module7_donnees.zip)
* [Module 8](https://github.com/sci1031/sci1031/blob/master/Module8/Module8_donnees.zip)
* [Module 9](https://github.com/sci1031/sci1031/blob/master/Module9/Module9_donnees.zip)

<br>

#### Autres sources {-}

Cette rubrique répertorie différentes bases de données qui contiennent des données spatiales.   


* [Données Québec](https://www.donneesquebec.ca/)
* [Données ouvertes du Gouvernement du Canada](https://ouvert.canada.ca/fr/donnees-ouvertes)
* [Répertoire de données spatiales de l'Université Laval](https://www.bibl.ulaval.ca/geostat/donnees_geospatiales/)
* [Répertoire de données spatiales de l'Université Sherbrooke](https://www.usherbrooke.ca/biblio/trouver-des/donnees-geospatiales/ressources-par-themes)
* [Répertoire de données spatiales de l'Université du Texas à Austin](https://geodata.lib.utexas.edu/catalog/facet/dc_subject_sm)
* [Données de la Banque Mondiale](https://databank.worldbank.org/home.aspx)
* [Données de la Commission Européenne sur l'urbanisation de la planète](https://ghsl.jrc.ec.europa.eu/index.php)  
* [Données de déplacement UBER](https://movement.uber.com/?lang=en-CA)

Vous êtes tombé sur une base de données intéressante qui ne figure pas plus bas? Partagez avec moi votre découverte et je l'ajouterai à cette liste.
