---
title: "Feuille de route"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, echo = FALSE, warning = FALSE}
data <- read.table("FeuilleRoute.csv", sep = ",", header = FALSE )
#col.names = c("","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15")
#data <- as.character(data)
#dim(data)
#as.character(data[1,])
#col.names = c("nom","s1","s2","s3","s4","s5","s6","s7","s8","s9","s10","s11","s12","s13","s14","s15")
#colnames(data) <- col.names
colnames(data) <- NULL
#head(data)

#data <- data[2:nrow(data),]
#dim(data)
```



```{r, echo = FALSE, warning = FALSE}
library(kableExtra)
#library(formattable)

#data[1]<-cell_spec(data[1],  background = "grey") # test, pis ca marche pas du tout
opts <- options(knitr.kable.NA = "", knitr.table.format = "simple")
#knitr::kable(data) %>%
kbl(data,"html", align = c("l",rep("c",15))) %>% #,align = "c" 
  kable_classic()%>%
  #kable_styling(bootstrap_options = c("responsive")) %>%
   add_header_above(c("", " 1"=1, " 2"=1," 3"=1, " 4"=1, " 5"=1, " 6"=1, 
                      " 7"=1, " 8"=1," 9"=1, "10"=1, "11"=1,"12"=1, "13"=1, "14"=1,"15"=1)) %>% 
  add_header_above(c("Modules" = 1, "Semaines" = 15)) %>%
  #add_indent(c(2, 4, 6, 8, 10, 13, 16, 18, 21)) %>% 
  column_spec(1:16, background = "white", border_right = "1px solid black") %>%
  column_spec(2:16, width = "0.5cm")  %>%
  column_spec(1, width = "6cm")  %>%
  column_spec(2, background = c("lightgrey", "lightgrey", rep("white",8), "lightpink", rep("white",11)) ) %>%
  column_spec(3, background = c("white", "white", "lightgrey", "lightgrey", rep("white",6), "lightpink", rep("white",11)) ) %>%
  column_spec(4, background = c(rep("white",4), "lightgrey", "lightgrey", rep("white",4), "lightpink", rep("white",11)) ) %>%
  column_spec(5, background = c(rep("white",6), "lightgrey", "lightgrey", rep("white",2), "lightpink", rep("white",11)) ) %>%
  column_spec(6, background = c(rep("white",8), "lightgrey", "lightgrey", "lightpink", rep("white",11)) ) %>%
  column_spec(c(7,8,9), background = c(rep("white",11), "lightgrey", "lightgrey", "lightpink", rep("white",8)) ) %>%
  #column_spec(8, background = c(rep("white",11), "lightgrey", "lightgrey", "lightpink", rep("white",10)) ) %>%
  column_spec(c(10, 11), background = c(rep("white",14), "lightgrey", "lightgrey", "white", "white","lightpink", rep("white",3)) ) %>%
  column_spec(c(12,13), background = c(rep("white",16), "lightgrey", "lightgrey", "lightpink", rep("white",3)) ) %>%
  column_spec(c(14,15), background = c(rep("white",19), "lightgrey", "lightgrey",  rep("white",1)) ) %>%
  column_spec(c(16), background = c(rep("white",21), "lightpink") ) %>%
  row_spec(c(11,14, 19, 22), bold = T, color = "red") %>%
  row_spec(c(1,3,5,7,9,12, 15,17, 20), bold = T)%>%
  row_spec(c(2,4,6,8,10,11,13, 14,16,18,19, 21), extra_css = "border-bottom: 1px solid black")
  #pack_rows( index = c("Module 1" = 1, "Module 2" = 1, "Module 3" = 1, "Module 4" = 1, "Module 5" = 1, "Travail noté 1" = 1),label_row_css = "background-color: #666; color: #fff;")



```

