# Manipulation de données matricielles {#manip_mat}


L'objectif principal de ce module est

À la fin de ce module vous saurez:

-
-
-

Vous utiliserez les librairies suivantes:

-
-

Vous apprendrez à utiliser les fonctions suivantes:

-
-

Dans la section Leçon, vous utiliserez des données XYXYX

Dans la section Exercice, vous utiliserez XXXXX

```{r load-libraries8, echo = FALSE, results='hide', warning = FALSE, message = FALSE}
library(raster)
library(sf)
```

### Importation du raster

### Accéder au valeur

- raster[1:100]
- accéder au coordonnées
- cellFromXY(elev, xy = c(0.1, 0.1))

Exemple avec les NAs
- remplacer les valeurs

### Modifier le contenu

- reclassify les valeurs (faible, modéré, élevé)

Décontextualisation par la perte des coordonnées X-Y, On privilégie l'approche:

- as.data.frame(xy = TRUE)

### Interaction avec un objet vectorielle

- crop et mask

### Extraire les valeurs

- extract


### Opération sur un raster

-	Extraction d’un sous-ensemble de données, suppression de données, modification de données, changement de position

### Opération sur plusieurs rasters

-	Combinaison de rasters, jointure spatiale, intersection de couches, découpage d’une couche.

## Exercice