# Manipulation de données vectorielles {#manip_vec}


L'objectif principal de ce module est

À la fin de ce module vous saurez:

-
-
-

Vous utiliserez les librairies suivantes:

-
-

Vous apprendrez à utiliser les fonctions suivantes:

-
-

Dans la section Leçon, vous utiliserez des données XYXYX

Dans la section Exercice, vous utiliserez XXXXX

```{r load-libraries7, echo = FALSE, results='hide', warning = FALSE, message = FALSE}
#library(raster)
library(rgdal)
library(ggplot2)
library(dplyr)
library(sf)
library(svglite) ## J'ai pas besoin de ça pour créer les figures, mais pour les inclure dans le markdown, oui.
library(ggpubr)
```


## Leçon

### Opérations de base

-	Supprimer des champs, ajouter des champs, modifier des valeurs de champs, trier la table des attributs.

### Opération sur une couche vectorielle

-	Jointure par identifiant, suppression de données, extraction par attributs, dissolution de polygones.

### Opération sur plusieurs couches vectorielles

-	Combinaison de couches, jointure spatiale, intersection de couches, découpage d’une couche.


## Exercice


