# Données spatiotemporelles {#spatiotemp}


L'objectif principal de ce module est

À la fin de ce module vous saurez:

- 
- 
-

Vous utiliserez les librairies suivantes:

-
-

Vous apprendrez à utiliser les fonctions suivantes:

-
-

Dans la section Leçon, vous utiliserez des données XYXYX

Dans la section Exercice, vous utiliserez XXXXX

```{r load-libraries9, echo = FALSE, results='hide', warning = FALSE, message = FALSE}
#library(raster)
library(rgdal)
library(ggplot2)
library(dplyr)
library(sf)
library(svglite) ## J'ai pas besoin de ça pour créer les figures, mais pour les inclure dans le markdown, oui.
library(ggpubr)
```


## Leçon

### Propriétés des données spatio-temporelles

Les données spatio-temporelles représente une collection d'objets spatiaux ordonnées dans le temps: la même information spatiales pour différents dans le temps. 


- Trajets en vélo (vitesse, distance) - POINT + LINES
    - GeoJSON
    - https://donnees.montreal.ca/ville-de-montreal/pistes-cyclables
- Étendue spatial du réseau de pistes cyclabes à travers le temps.
- Expansion des aires protégées au Québec
    -  https://www.donneesquebec.ca/recherche/fr/dataset/aires-protegees-au-quebec


### Visualisation spatiotemporelle

-	Figure à panneaux multiples
-	Figure espace-temps
    - Hovmoller plot
-	Figure animée


### Introduction à la librairie R stars

-	Classes de données spatiotemporelles
-	Création d’objet ST
-	Manipulation de bases de données spatiotemporelles




## Exercice

