# Les données matricielles {#mat}


L'objectif principal de ce module est

À la fin de ce module vous saurez:

-
-
-

Vous utiliserez les librairies suivantes:

-
-

Vous apprendrez à utiliser les fonctions suivantes:

-
-

Dans la section Leçon, vous utiliserez des données XYXYX

Dans la section Exercice, vous utiliserez XXXXX

```{r load-libraries4, echo = FALSE, results='hide', warning = FALSE, message = FALSE}
#library(raster)
library(rgdal)
library(ggplot2)
library(dplyr)
library(sf)
library(svglite) ## J'ai pas besoin de ça pour créer les figures, mais pour les inclure dans le markdown, oui.
library(ggpubr)
```


## Leçon

### Introduction aux données matricielles sous R

- Lire et explorer les attributs d’un raster
-	Comprendre le SCR
-	Gérer les données manquantes et les mauvaises données
-	Raster mono-bande et multi-bande
-	Écrire des données matricielles

### Visualisation de rasters sous R

-	Utiliser ggplot pour visualiser les rasters
-	Visualiser plusieurs couches matricielles
- Visualiser des données matricielles et vectorielles au sein d’une même figure

### Reprojection de données matricielles sous R

-	Manipuler le SCR
-	Manipuler la résolution

### Manipulation de rasters multi-bande sous R

-	Visualiser des rasters multi-bande
-	Manipuler des objets RasterStack
-	Manipuler des objets RasterBrick

## Exercice
